{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e836102-5617-4a08-a7b0-a160fc259254",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import the dependencies.\n",
    "from Flask import Flask, jsonify\n",
    "from flask import Flask, jsonify, render_template\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sqlHelper import SQLHelper\n",
    "\n",
    "#################################################\n",
    "# Flask Setup\n",
    "#################################################\n",
    "app = Flask(__name__)\n",
    "sql = SQLHelper()\n",
    "\n",
    "#################################################\n",
    "# Flask Routes\n",
    "#################################################\n",
    "\n",
    "# HTML ROUTES\n",
    "@app.route(\"/\")\n",
    "def index():\n",
    "    return render_template(\"home.html\")\n",
    "\n",
    "@app.route(\"/dashboard\")\n",
    "def dashboard():\n",
    "    return render_template(\"dashboard.html\")\n",
    "\n",
    "@app.route(\"/map\")\n",
    "def map():\n",
    "    return render_template(\"map.html\")\n",
    "\n",
    "@app.route(\"/about_us\")\n",
    "def about_us():\n",
    "    return render_template(\"about_us.html\")\n",
    "\n",
    "# SQL Queries\n",
    "@app.route(\"/api/v1.0/get_dashboard/<min_attempts>/<region>\")\n",
    "def get_dashboard(min_attempts, region):\n",
    "    min_attempts = int(min_attempts) # cast to int\n",
    "\n",
    "    bar_data = sql.get_bar(min_attempts, region)\n",
    "    pie_data = sql.get_pie(min_attempts, region)\n",
    "    table_data = sql.get_table(min_attempts, region)\n",
    "\n",
    "    data = {\n",
    "        \"bar_data\": bar_data,\n",
    "        \"pie_data\": pie_data,\n",
    "        \"table_data\": table_data\n",
    "    }\n",
    "    return(jsonify(data))\n",
    "\n",
    "@app.route(\"/api/v1.0/get_map/<min_attempts>/<region>\")\n",
    "def get_map(min_attempts, region):\n",
    "    min_attempts = int(min_attempts) # cast to int\n",
    "    map_data = sql.get_map(min_attempts, region)\n",
    "\n",
    "    return(jsonify(map_data))\n",
    "\n",
    "\n",
    "\n",
    "# Run the App\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
